# Generated by Django 4.2.16 on 2024-10-06 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoClass',
            new_name='Todo',
        ),
    ]
